modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="mcalecs_changed_addon"
version="0.1"
displayName="McAlec's Changed Addon"
credits="McAlec"
displayURL="https://curseforge.com/minecraft/mc-mods/mcalecs-changed-addon"
logoFile="logo.png"
authors="McAlec"
description="Test"

[[dependencies.mcalecs_changed_addon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




