modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="mcalecs_changed_addon"
version="0.2"
displayName="McAlec's Changed Addon"
credits="McAlec"
displayURL="https://modrinth.com/mod/mcalecs-changed-addon"
logoFile="logo.png"
authors="McAlec"
description="Addon Mod to LtxProgrammer's Changed: MC Mod"

[[dependencies.mcalecs_changed_addon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




